### ISSUE TITLE
Error when installing the project - SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by ordavidil** [Gizra/productivity#492]
When trying to install the project locally I get this error:
```sh
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE     [error]
instead' in /Applications/MAMP/htdocs/productivity/www/includes/database/database.inc:2227
Stack trace:
#0 /Applications/MAMP/htdocs/productivity/www/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /Applications/MAMP/htdocs/productivity/www/includes/database/database.inc(697): DatabaseStatementBase->execute(Array, Array)
#2 /Applications/MAMP/htdocs/productivity/www/includes/database/schema.inc(667): DatabaseConnection->query('CREATE TABLE {m...')
#3 /Applications/MAMP/htdocs/productivity/www/includes/database/database.inc(2776): DatabaseSchema->createTable('message', Array)
#4 /Applications/MAMP/htdocs/productivity/www/includes/common.inc(7131): db_create_table('message', Array)
#5 /Applications/MAMP/htdocs/productivity/www/includes/module.inc(479): drupal_install_schema('message')
#6 /Applications/MAMP/htdocs/productivity/www/includes/install.core.inc(1609): module_enable(Array, false)
#7 [internal function]: _install_module_batch('message', 'Message', Array)
#8 /Applications/MAMP/htdocs/productivity/www/includes/batch.inc(284): call_user_func_array('_install_module...', Array)
#9 /Applications/MAMP/htdocs/productivity/www/includes/form.inc(4714): _batch_process()
#10 /Applications/MAMP/htdocs/productivity/www/includes/install.core.inc(444): batch_process('install.php?pro...', 'http://producti...')
#11 /Applications/MAMP/htdocs/productivity/www/includes/install.core.inc(339): install_run_task(Array, Array)
#12 /Applications/MAMP/htdocs/productivity/www/includes/install.core.inc(77): install_run_tasks(Array)
#13 /Users/ordavid/.composer/vendor/drush/drush/includes/drush.inc(725): install_drupal(Array)
#14 /Users/ordavid/.composer/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#15 /Users/ordavid/.composer/vendor/drush/drush/commands/core/drupal/site_install_7.inc(86): drush_op('install_drupal', Array)
#16 /Users/ordavid/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('productivity', Array)
#17 [internal function]: drush_core_site_install('productivity', 'install_configu...')
#18 /Users/ordavid/.composer/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_core_site...', Array)
#19 /Users/ordavid/.composer/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#20 [internal function]: drush_command('productivity', 'install_configu...')
#21 /Users/ordavid/.composer/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#22 /Users/ordavid/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#23 /Users/ordavid/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#24 /Users/ordavid/.composer/vendor/drush/drush/drush.php(12): drush_main()
#25 {main}
```

Seems like a schema issue in the `message` module.

**Comment by ordavidil** [comment]
Currently we use version `1.11` of the message module although `1.12` is already released.

**Comment by ordavidil** [comment]
Updating the version solved the problem, creating a PR.
